FROM UBUNTU:16.04
FROM PYTHON:3.7


COPY requirements.txt /

COPY model.h5 /
COPY test /

COPY weights_flowers_1.hdf5 /

RUN pip install -r / requirements.txt

COPY inference.py /
RUN chmod u+x ./inference.py

CMD ./inference.py